#!/usr/bin/env python3
"""Analyze NEW randomized butterfly food-clamp experiment, if and only if real records exist.

No synthetic ecological outcomes are generated by this program. Input data are
four separate field ledgers, all plant/enclosure-level assignment checks are
fail closed, and all originally assigned larvae (including attrition) remain in
the ITT denominator. Any point contrast is NOT proof of a biomass-only mechanism.
"""
from __future__ import annotations
import argparse
import csv
import hashlib
import json
import math
import random
from collections import Counter,defaultdict
from datetime import datetime
from pathlib import Path

ARMS={
    "NATURAL_NO_COMPETITOR":(0,0),
    "NATURAL_COMPETITOR":(1,0),
    "CLAMP_NO_COMPETITOR":(0,1),
    "CLAMP_COMPETITOR":(1,1),
}
SUCCESS="flight_capable_adult"
FAIL={"adult_nonflight","dead_immature","pupa_no_adult"}
UNKNOWN={"lost_to_followup","other_documented"}
OUTCOME_VALUES={SUCCESS}|FAIL|UNKNOWN
FATE_COLS=["plant_id","larva_id","species","fate"]
INFO_COLS=["plant_id","block_id","treatment","competitor_present","food_clamp",
           "native_initial_n","competitor_initial_n","food_floor_cm2","expected_n_resource_visits"]
RESOURCE_COLS=["plant_id","observation_datetime","accessible_leaf_area_cm2","fresh_leaf_area_added_cm2"]

def csv_source(p:Path,cols:list[str]):
    with p.open(encoding="utf-8-sig",newline="") as fh:
        reader=csv.DictReader(fh)
        if reader.fieldnames!=cols:
            raise ValueError(f"{p}: expected EXACT columns: {cols}; got {reader.fieldnames}")
        items=list(reader)
    if not items:raise ValueError(f"{p}: empty ledger")
    return items

def finite_nonnegative(v,field,allow_blank=False):
    raw=str(v or "").strip()
    if not raw and allow_blank:return None
    try:x=float(raw)
    except ValueError:raise ValueError(f"{field}: missing/bad nonnegative number")
    if not math.isfinite(x) or x<0:raise ValueError(f"{field}: nonfinite/negative")
    return x

def nonnegative_int(v,field,positive=False):
    val=finite_nonnegative(v,field)
    if val!=int(val) or (positive and val==0):
        raise ValueError(f"{field}: not an eligible integer")
    return int(val)

def canonical_assignment(info,allocation):
    allot={}
    for r in allocation:
        id_=r["plant_id"]
        if not id_ or id_ in allot:raise ValueError("blank/duplicate randomized plant ID")
        allot[id_]=r
    plants={}
    for r in info:
        plant=r["plant_id"]
        if not plant or plant in plants:raise ValueError("blank/duplicate experiment plant ID")
        if plant not in allot:raise ValueError(f"unrandomized plant: {plant}")
        arm=r["treatment"]
        if arm not in ARMS:raise ValueError("unknown treatment name")
        assigned=allot[plant]
        if any(r[k]!=assigned[k] for k in ("block_id","treatment","competitor_present","food_clamp")):
            raise ValueError(f"post-allocation treatment/block mismatch: {plant}")
        competitor,clamp=ARMS[arm]
        if (nonnegative_int(r["competitor_present"],"competitor_present"),
            nonnegative_int(r["food_clamp"],"food_clamp"))!=(competitor,clamp):
            raise ValueError(f"treatment factor mismatch: {plant}")
        native=nonnegative_int(r["native_initial_n"],"native_initial_n",positive=True)
        hetero=nonnegative_int(r["competitor_initial_n"],"competitor_initial_n")
        if (hetero>0)!=bool(competitor):
            raise ValueError(f"competitor density does not match assignment: {plant}")
        nvisit=nonnegative_int(r["expected_n_resource_visits"],"expected_n_resource_visits",positive=True)
        if nvisit<2:raise ValueError("each cage needs >=2 prospective observations")
        target=finite_nonnegative(r["food_floor_cm2"],"food_floor_cm2")
        if target==0:raise ValueError("food floor must be measured and >0")
        plants[plant]={**r,"native_initial_n":native,"competitor_initial_n":hetero,
                       "expected_n_resource_visits":nvisit,"food_floor_cm2":target}
    if set(plants)!=set(allot):
        raise ValueError("missing randomized plants cannot be excluded after outcomes")
    blocks=defaultdict(list)
    for r in plants.values():
        blocks[r["block_id"]].append(r)
    for block,rs in blocks.items():
        counts=Counter(x["treatment"] for x in rs)
        if len(counts)!=4 or len(set(counts.values()))!=1:
            raise ValueError(f"unbalanced/randomization-unit missing block {block}")
        if len(set(x["food_floor_cm2"] for x in rs))!=1:
            raise ValueError(f"original food floor not fixed within block {block}")
        if len(set(x["expected_n_resource_visits"] for x in rs))!=1:
            raise ValueError(f"observation effort not balanced within block {block}")
    return plants,blocks

def fate_tally(plants,fates):
    byplant=defaultdict(list)
    larvaids=set()
    for r in fates:
        plant=r["plant_id"]
        if plant not in plants:raise ValueError(f"unknown fate plant: {plant}")
        id_=r["larva_id"]
        if not id_ or id_ in larvaids:raise ValueError("duplicate/missing original larva ID")
        larvaids.add(id_)
        if r["species"]!="Atrophaneura alcinous":
            raise ValueError("primary ledger must contain only originally assigned native recipients")
        if r["fate"] not in OUTCOME_VALUES:
            raise ValueError("unknown outcome code")
        byplant[plant].append(r["fate"])
    out={}
    for plant,p in plants.items():
        vals=byplant.get(plant,[])
        if len(vals)!=p["native_initial_n"]:
            raise ValueError(f"{plant}: cannot drop or add originally randomized larvae")
        counts=Counter(vals)
        n=p["native_initial_n"]
        success=counts[SUCCESS]
        uncertain=sum(counts[k] for k in UNKNOWN)
        out[plant]={
            "n_initial":n,"known_adult_success":success,
            "known_failure":sum(counts[k] for k in FAIL),
            "outcome_unknown":uncertain,
            "lower_bound":success/n,
            "upper_bound":(success+uncertain)/n,
        }
    return out

def resource_tally(plants,visits):
    byplant=defaultdict(list)
    seen=set()
    for r in visits:
        plant=r["plant_id"]
        if plant not in plants:raise ValueError("unrandomized visit")
        date=r["observation_datetime"].strip()
        try:dt=datetime.fromisoformat(date)
        except ValueError:raise ValueError(f"invalid ISO timestamp {date}")
        if dt.tzinfo is None:raise ValueError("resource time must include UTC offset")
        key=(plant,dt.isoformat())
        if key in seen:raise ValueError("duplicate scheduled plant occasion")
        seen.add(key)
        area=finite_nonnegative(r["accessible_leaf_area_cm2"],"accessible_leaf_area_cm2",True)
        added=finite_nonnegative(r["fresh_leaf_area_added_cm2"],"fresh_leaf_area_added_cm2",True)
        byplant[plant].append((dt,area,added))
    out={}
    for plant,p in plants.items():
        rows=sorted(byplant.get(plant,[]))
        if len(rows)!=p["expected_n_resource_visits"]:
            raise ValueError(f"{plant}: missing extra/fewer scheduled resource visits")
        observed=[a for _,a,_ in rows if a is not None]
        supplemented=[v for _,_,v in rows if v is not None]
        out[plant]={
            "scheduled_visits":len(rows),
            "n_observed_accessible_area":len(observed),
            "missing_accessible_area":len(rows)-len(observed),
            "visits_below_preset_floor":sum(v<p["food_floor_cm2"] for v in observed),
            "fraction_below_floor_observed":(
                sum(v<p["food_floor_cm2"] for v in observed)/len(observed) if observed else None
            ),
            "total_added_fresh_leaf_area_cm2":sum(supplemented),
            "missing_added_area":len(rows)-len(supplemented)
        }
    return out

def block_differences(plants,blocks,stats,key="lower_bound"):
    vals=[]
    for block,rs in sorted(blocks.items()):
        means={arm:sum(stats[r["plant_id"]][key] for r in rs if r["treatment"]==arm)/
                      sum(r["treatment"]==arm for r in rs) for arm in ARMS}
        val=(means["CLAMP_COMPETITOR"]-means["CLAMP_NO_COMPETITOR"] -
             means["NATURAL_COMPETITOR"]+means["NATURAL_NO_COMPETITOR"])
        vals.append({"block_id":block,"interaction":val,"arm_risks":means})
    return vals

def bootstrap(vals,seed=20261010,draws=2000):
    if len(vals)<3:
        return None
    rng=random.Random(seed)
    numbers=[v["interaction"] for v in vals]
    res=[]
    for _ in range(draws):
        res.append(sum(numbers[rng.randrange(len(numbers))] for _ in numbers)/len(numbers))
    res.sort()
    return [res[int(.025*draws)],res[int(.975*draws)]]

def analyze(allocation,info,fates,visits):
    plants,blocks=canonical_assignment(info,allocation)
    ends=fate_tally(plants,fates)
    quality=resource_tally(plants,visits)
    effect=block_differences(plants,blocks,ends,"lower_bound")
    upper=block_differences(plants,blocks,ends,"upper_bound")
    perarm={}
    for arm in ARMS:
        ids=[plant for plant,r in plants.items() if r["treatment"]==arm]
        succ=sum(ends[p]["known_adult_success"] for p in ids)
        assigned=sum(ends[p]["n_initial"] for p in ids)
        missing=sum(ends[p]["outcome_unknown"] for p in ids)
        obs=sum(quality[p]["n_observed_accessible_area"] for p in ids)
        below=sum(quality[p]["visits_below_preset_floor"] for p in ids)
        additions=sum(quality[p]["total_added_fresh_leaf_area_cm2"] for p in ids)
        perarm[arm]={
            "independent_cages":len(ids),"original_focal_larvae":assigned,
            "successful_flight_capable_adults":succ,"unknown_fate":missing,
            "lower_bound_success":succ/assigned,
            "upper_bound_success":(succ+missing)/assigned,
            "observed_food_visits":obs,"visits_below_food_floor":below,
            "fraction_observed_below_floor":below/obs if obs else None,
            "missing_food_measurements":sum(quality[p]["missing_accessible_area"] for p in ids),
            "total_added_fresh_leaf_area_cm2":additions,
        }
    lower=sum(z["interaction"] for z in effect)/len(effect)
    upper=sum(z["interaction"] for z in upper)/len(upper)
    complete=all(ends[p]["outcome_unknown"]==0 for p in plants)
    return {
        "schema":"chocho_kyoto_food_clamp_outcomes_v01",
        "randomization_unit":"whole plant/enclosure",
        "n_independent_plants":len(plants),"n_blocks":len(blocks),
        "per_arm":perarm,
        "block_level_lower_bound_interactions":effect,
        "ITT_lower_missing_as_fail_interaction":lower,
        "ITT_upper_missing_as_success_interaction":upper,
        "independent_block_bootstrap_95ci_for_lower_bound":bootstrap(effect),
        "all_native_cohort_fates_known":complete,
        "resource_manipulation_achieved":"NOT_AUTOMATICALLY_IDENTIFIABLE_FROM_SOURCE_LEDGER; inspect arm contrasts and tissue quality",
        "does_not_condition_on_supplement_success":True,
        "nonresource_mechanism_causally_identified":False,
        "host_plant_intro_not_tested":True,
        "GEB_PR38_unchanged":True
    }

def main():
    ap=argparse.ArgumentParser()
    for name in ("allocation","assignments","fates","resource","receipt"):
        ap.add_argument("--"+name,required=True,type=Path)
    args=ap.parse_args()
    alloc=csv_source(args.allocation,["plant_id","block_id","treatment",
                                        "competitor_present","food_clamp","random_seed","design_version"])
    result=analyze(alloc,csv_source(args.assignments,INFO_COLS),
                   csv_source(args.fates,FATE_COLS),csv_source(args.resource,RESOURCE_COLS))
    paths={k:str(getattr(args,k)) for k in ("allocation","assignments","fates","resource")}
    result["input_sha256"]={k:hashlib.sha256(Path(p).read_bytes()).hexdigest() for k,p in paths.items()}
    args.receipt.parent.mkdir(parents=True,exist_ok=True)
    args.receipt.write_text(json.dumps(result,indent=2)+"\n",encoding="utf-8")
    print(json.dumps(result,indent=2))

if __name__=="__main__":
    main()
